### ISSUE TITLE
Switch Kernal with a number keys?

### ISSUE THREAD

**Issue by danko79** [bwack/C64-Switchless-Multi-Kernal-27C256-adapter#11]
Hi, is it possible made an alternative firmware, which allows switch the kernals by pressing the number keys associated with a specific kernals?

**Comment by gh0stless** [comment]
No

**Comment by bwack** [comment]
Check out Sven Petersens project. He has a feature like the one you describe.

**Comment by danko79** [comment]
Hi, i have a Sven Petersen project many thanks!
