### ISSUE TITLE
Cannot find Gerber files

### ISSUE THREAD

**Issue by vk5ln** [bwack/C64-Switchless-Multi-Kernal-27C256-adapter#6]
I hope this is not a silly question... but I cannot seem to find Gerber files for the SKS64 Switchless Multi Kernal Switcher
Can someone point me to the right place to find them?

**Comment by bwack** [comment]
They are under Releases. 
https://github.com/bwack/C64-Switchless-Multi-Kernal-27C256-adapter/releases/tag/V1.21
May I ask which board you are making ? Are you making for the 1541C/II, if so, I'm currently working on a solution for the 1541C/1541-II.

**Comment by vk5ln** [comment]
Thank you for that.  I did see mention of a Releases Tab, but didn't see it. 
I'm planning on making Kernal switchers for both C64 Long and Short Boards.
