### ISSUE TITLE
Newer releases not working with shortboard v1.0 PCB

### ISSUE THREAD

**Issue by glbyers** [bwack/C64-Switchless-Multi-Kernal-27C256-adapter#7]
I have the SKS in a 250469 with the revsion 1.0 PCB. I built this about a year ago and asidfe from black screen on initial boot, would work fine after changing kernel or reset. I saw v1.2 release should fix this, so updated to the latest release (v1.4). Since doing that, I don't seem to be able to do the initial setup. On power up, I get cycles of 1 long flash followed by 2 short flashes and it doesn't matter how long I hold RESET for on power up, that does not change. I downgraded to release 1.2, but still observed the same behaviour. I'm using a W27C512 with BASIC followed by 7 kernels and an ATTINY85, the same setup that previously worked. I re-flashed v1.1 and I was again able to run the setup and aside from black screen at startup, works fine again after initial reset or kernel change.

**Comment by bwack** [comment]
Try 1.6
https://github.com/bwack/C64-Switchless-Multi-Kernal-27C256-adapter/releases/tag/fw1.6

**Comment by glbyers** [comment]
Worked beautifully. Thanks so much!

**Comment by bwack** [comment]
Thank you too. I had forgotten to release the latest hex files.
