### ISSUE TITLE
New firmware

### ISSUE THREAD

**Issue by C64Retro** [bwack/C64-Switchless-Multi-Kernal-27C256-adapter#8]
Hi
Can someone please include the latest hex firmware (V1.6 I think) in a format suitable for programming with the TL866ii programmer.
Thanks in advance.

**Comment by bwack** [comment]
OK. I'm updating the releases now.

**Comment by bwack** [comment]
https://github.com/bwack/C64-Switchless-Multi-Kernal-27C256-adapter/releases/tag/fw1.6

**Comment by C64Retro** [comment]
Thanks very much really appreciate it. Was trying to program using firmware V1.4 and low fuse byte E2 (8 MHz) but results in LED blinking once connected to C64. Had to use low fuse byte setting 62 (1MHz) as in instructions dated 03/15/2021 for firmware V1.4.

**Comment by bwack** [comment]
Ok. Let me know how it goes. This time you will need it to run at 8MHz.

**Comment by C64Retro** [comment]
HI
Thanks, I tried out and works fine using firmware V1.6 with shortboard V1.0. Winbond w27c512 set to 7 kernals.
I tried a number of kernals with a Pi1541 option B 3A+ drive and all good so far.
